server {
    listen 80;
    add_header X-Gateway $hostname always;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    location = /api/health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }

    location /api/authors { proxy_pass http://authors-service; include /etc/nginx/proxy_params.conf; }
    location /api/books   { proxy_pass http://books-service;   include /etc/nginx/proxy_params.conf; }
    location /api/members { proxy_pass http://members-service; include /etc/nginx/proxy_params.conf; }
    location /api/loans   { proxy_pass http://loans-service;   include /etc/nginx/proxy_params.conf; }
}
