apiVersion: v1
kind: Namespace
metadata:
  name: library
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: library
type: Opaque
stringData:
  POSTGRES_USER: library
  POSTGRES_PASSWORD: library_pass
